name: Build binaries

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    strategy:
      matrix:
        target:
          - x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          build/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y perl

    - name: Build
      run: cargo build --release --target=${{ matrix.target }}-unknown-linux-gnu

    - uses: actions/upload-artifact@v4
      with:
        name: proot-cri_linux_${{ matrix.target }}
        path: ./target/${{ matrix.target }}-unknown-linux-gnu/release/proot-cri

  build-android:
    strategy:
      matrix:
        api:
          - "30"
        target: 
          - x86_64
          - aarch64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          build/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-linux-android,aarch64-linux-android

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y perl

    - name: Build
      run: ANDROID_API=${{ matrix.api }} ARCH=${{ matrix.target }} ./hack/build-android.sh --release

    - uses: actions/upload-artifact@v4
      with:
        name: proot-cri_android${{ matrix.api }}_${{ matrix.target }}
        path: ./target/${{ matrix.target }}-linux-android/release/proot-cri
